language: php

php:
    - 5.3

install:
    - composer self-update
    - composer install

script:
    - php -d xdebug.max_nesting_level=255 vendor/bin/behat
    - vendor/bin/phpspec run
    - vendor/bin/phpcs -p --colors --standard=PSR2 src/ features/bootstrap/
    - vendor/bin/phpcs -p --colors --standard=vendor/jakubzapletal/php_codesniffer-rules/psr2-without-camel-case-method-name.xml spec/
